# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Pixelated API
  description: API Description for the Pixelated Leaf Development Client
  version: "0.0.1"
# the domain of the service
host: localhost:3333
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /mails:
    get:
      summary: List of Mails
      description: |
        Return a list of mails
      parameters:
        - name: q
          in: query
          description: Which folder to show. "tag:inbox"
          required: true
          type: string
        - name: p
          in: query
          description: Which page do we want to see
          required: true
          type: number
          format: Int32
        - name: w
          in: query
          description: How many items do we want to have returned
          required: true
          type: number
          format: integer
      tags:
        - Mails
      responses:
        200:
          description: An array of mails
          schema:
            $ref: '#/definitions/MailEnvelope'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Creates a mail draft
      description: |
        Creates a new mail draft
      parameters:
        - name: mail
          in: body
          schema:
            $ref: '#/definitions/Mail'
      tags:
        - Mails
      responses:
        200:
          description: A new mail identifier
          schema:
            properties:
              ident:
                $ref: '#/definitions/MailIdent'
    post:
      summary: Sends a mail
      description: |
        Sends a mail. The mail ident of the response may be different to the one specified in body.
      tags:
        - Mails
      parameters:
        - name: mail
          in: body
          schema:
            $ref: '#/definitions/Mail'
      responses:
        200:
          description: The specified mail
          schema:
            $ref: '#/definitions/Mail'
  /mail/{ident}:
    get:
      summary: Gets mail details
      description: |
        Return details of a specific mail
      parameters:
        - name: ident
          in: path
          description: Identifier of mail
          required: true
          type: string
      tags:
        - Mail
      responses:
        200:
          description: The specified mail
          schema:
            $ref: '#/definitions/Mail'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Deletes a mail
      description: |
        On first call it moves the mail into the 'trash' folder, on second call the mail is deleted.
      parameters:
        - name: ident
          in: path
          description: Identifier of mail
          required: true
          type: string
      tags:
        - Mail
      responses:
        200:
          description: Returns 'null'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /mail/{ident}/tags:
    post:
      summary: Changes tags of a mail
      description: |
        Changes the list of tags of a specific mail
      parameters:
        - name: ident
          in: path
          description: Identifier of mail
          required: true
          type: string
        - name: newtags
          in: body
          description: List of tags
          required: true
          schema:
            $ref: '#/definitions/MailTagsEnvelope'
      tags:
        - Mail
        - Tags
      responses:
        200:
          description: An array of mails
          schema:
            $ref: '#/definitions/Mail'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /contacts:
    get:
      summary: Contact suggestions
      description: |
        Returns contact suggestions for the given query
      parameters:
        - name: q
          in: query
          description: Substring of a contact
          required: true
          type: string
      tags:
        - Contacts
      responses:
        200:
          description: An array of matching contacts
          schema:
            $ref: '#/definitions/RecipientList'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /tags:
    get:
      summary: List of Tags
      description: |
        Return a list of available tags
      parameters:
        - name: q
          in: query
          description: Filter tags by name. Query only filters custom tags
          required: false
          type: string
        - name: skipDefaultTags
          in: query
          description: Whether to show default tags (trash, inbox, sent, drafts).
          required: false
          type: boolean
      tags:
        - Tags
      responses:
        200:
          description: An array of tags
          schema:
            $ref: '#/definitions/TagEnvelope'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  MailIdent:
    type: string
  MailEnvelope:
    properties:
      mails:
        type: array
        items:
          $ref: '#/definitions/Mail'
  Mail:
    properties:
      status:
        type: array
        items:
          type: string
      header:
        properties:
          from:
            type: string
          cc:
            type: array
            items:
              type: string
          to:
            type: array
            items:
              type: string
          content-type: 
            type: string
          date:
            type: string
          subject:
            type: string
      ident:
        $ref: '#/definitions/MailIdent'
      replying:
        properties:
          single:
            $ref: '#/definitions/Recipient'
          all:
            properties:
              to-field:
                $ref: '#/definitions/RecipientList'
              to-field:
                $ref: '#/definitions/RecipientList'
      textPlainBody:
        type: string
      tags:
        type: array
        items:
          type: string
      mailBox:
        type: string
  RecipientList:
    type: array
    items:
      $ref: '#/definitions/Recipient'
  Recipient:
    type: string
  MailTagsEnvelope:
    properties:
      newtags:
        type: array
        items:
          type: string
  TagEnvelope:
    type: array
    items:
      $ref: '#/definitions/Tag'
  Tag:
    properties:
      default:
        type: boolean
      mails:
        type: array
        items:
          $ref: '#/definitions/MailIdent'
      count:
        properties:
          read:
            type: number
            format: int32
          total:
            type: number
            format: int32
      ident:
        type: string
      name:
        type: string
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
