# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Pixelated API
  description: API Description for the Pixelated Leaf Development Client
  version: "0.0.1"
# the domain of the service
host: localhost:3333
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /mails:
    get:
      summary: List of Mails
      description: |
        Return a list of mails
      parameters:
        - name: q
          in: query
          description: Which folder to show. "tag:inbox"
          required: true
          type: string
        - name: p
          in: query
          description: Which page do we want to see
          required: true
          type: number
          format: Int32
        - name: w
          in: query
          description: How many items do we want to have returned
          required: true
          type: number
          format: integer
      tags:
        - Mails
      responses:
        200:
          description: An array of mails
          schema:
            $ref: '#/definitions/MailEnvelope'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /tags:
    get:
      summary: List of Tags
      description: |
        Return a list of available tags
      parameters:
        - name: q
          in: query
          description: Filter tags by name. Query only filters custom tags
          required: false
          type: string
        - name: skipDefaultTags
          in: query
          description: Whether to show default tags (trash, inbox, sent, drafts).
          required: false
          type: boolean
      tags:
        - Tags
      responses:
        200:
          description: An array of tags
          schema:
            $ref: '#/definitions/TagEnvelope'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  MailIdent:
    type: string
  MailEnvelope:
    properties:
      mails:
        type: array
        items:
          $ref: '#/definitions/Mail'
  Mail:
    properties:
      status:
        type: array
        items:
          type: string
      header:
        properties:
          from:
            type: string
          cc:
            type: array
            items:
              type: string
          to:
            type: array
            items:
              type: string
          content-type: 
            type: string
          date:
            type: string
          subject:
            type: string
      ident:
        $ref: '#/definitions/MailIdent'
      textPlainBody:
        type: string
      tags:
        type: array
        items:
          type: string
      mailBox:
        type: string
  TagEnvelope:
    type: array
    items:
      $ref: '#/definitions/Tag'
  Tag:
    properties:
      default:
        type: boolean
      mails:
        type: array
        items:
          $ref: '#/definitions/MailIdent'
      count:
        properties:
          read:
            type: number
            format: int32
          total:
            type: number
            format: int32
      ident:
        type: string
      name:
        type: string
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
